export const designTokens = {
  radius: {
    xs: 8,
    sm: 12,
    md: 16,
    lg: 20,
    xl: 24,
    full: 9999,
  },
  spacing: {
    xs: 4,
    sm: 8,
    md: 12,
    lg: 16,
    xl: 20,
    xxl: 24,
    xxxl: 32,
  },
  shadows: {
    sm: {
      shadowColor: "#000",
      shadowOffset: { width: 0, height: 1 },
      shadowOpacity: 0.05,
      shadowRadius: 2,
      elevation: 1,
    },
    md: {
      shadowColor: "#000",
      shadowOffset: { width: 0, height: 3 },
      shadowOpacity: 0.08,
      shadowRadius: 6,
      elevation: 3,
    },
    lg: {
      shadowColor: "#000",
      shadowOffset: { width: 0, height: 6 },
      shadowOpacity: 0.1,
      shadowRadius: 12,
      elevation: 6,
    },
    colored: (color: string) => ({
      shadowColor: color,
      shadowOffset: { width: 0, height: 4 },
      shadowOpacity: 0.25,
      shadowRadius: 8,
      elevation: 5,
    }),
  },
  typography: {
    display: { fontSize: 32, lineHeight: 38, fontWeight: "800" as const },
    h1: { fontSize: 26, lineHeight: 32, fontWeight: "800" as const },
    h2: { fontSize: 22, lineHeight: 28, fontWeight: "700" as const },
    h3: { fontSize: 18, lineHeight: 24, fontWeight: "700" as const },
    body: { fontSize: 14, lineHeight: 20, fontWeight: "400" as const },
    bodyStrong: { fontSize: 14, lineHeight: 20, fontWeight: "600" as const },
    caption: { fontSize: 12, lineHeight: 16, fontWeight: "600" as const },
    overline: { fontSize: 10, lineHeight: 14, fontWeight: "800" as const, letterSpacing: 1.2 },
    small: { fontSize: 11, lineHeight: 15, fontWeight: "500" as const },
  },
  animation: {
    duration: {
      fast: 150,
      normal: 250,
      slow: 350,
      slower: 500,
    },
    easing: {
      standard: "ease-out",
      decelerate: "ease-out",
      accelerate: "ease-in",
      spring: "spring",
    },
  },
};
